---
title: "Implementation Study Analysis"
author: "Senegal data manager"
output: html_document
date: "2024-02-28"
--- 

```{r,echo=FALSE,results='hide'}

# install these packages if not already on your computer
library(plyr)
library(dplyr)
library(tableone)
library(knitr)
library(kableExtra)
library(epiDisplay)
library(Hmisc)


# Read in (cleaned) data
# Create a text file from within R with the name ".Renviron", then define the variables as below
# filename = "<current-file-name>.csv"
# COUNTRY = "<your-country>"
# After adding the file and content restart R session and you are good to go
# The Renviron will be ignored when pushing changes to Github

df_og <- read.csv2("C:/Users/user/Dropbox/Mon PC (DESKTOP-OMJATUN)/Desktop/TIMCI/Implamentation study training/implementation-data_clean_2024-02-15.csv")

# Define country and subset

df <- subset(df_og, df_og$country=="Senegal")

```
 
# Table 1: Patient demographic and household characteristics.


```{r,echo=FALSE,fig.show='hide'}
#CARACTERISTIQUES 

## Age
df$birthday<-as.Date(paste(df$birth_year,df$birth_month,"15",sep = "-"),format = "%Y-%m-%d")
df$visit_date_1=as.Date(df$visit_date,format = "%d/%m/%Y")
df$visit_date_2=format(df$visit_date_1,"%Y-%m-%d")
df$Age_categ = difftime(df$visit_date_2,df$birthday,units = "days")
df$age_m = df$Age_categ/30
df$age_m=as.numeric(df$age_m)
df$age_m_1 = cut(df$age_m,
             breaks = c(0,2,12,60),
             right = F,
             labels = c("0-1","2-11","12-59"))
describe(df$age_m_1)
tabpct(df$facility_name,df$age_m_1)
## Sex

df$sex=as.factor(df$sex)
describe(df$sex)
tabpct(df$facility_name,df$sex)

## Relationship of caregiver to child

describe(df$cg_relationship)
tabpct(df$facility_name,df$cg_relationship)

## Caregiver age
summ(df$cg_age)
 tapply(df$cg_age, df$facility_name, mean,na.rm=T)

## Maternal education
df$cg_edu_mother[df$cg_edu_mother==999] = NA
df$cg_edu_mother=as.factor(df$cg_edu_mother)
describe(df$cg_edu_mother) 
tabpct(df$facility_name,df$cg_edu_mother)

## Household head
df$household_head[df$household_head==99] = NA
df$household_head=as.factor(df$household_head)
describe(df$household_head)
tabpct(df$facility_name,df$household_head)

## Household toilet
df$household_toilet[df$household_toilet==999] = NA
df$household_toilet=as.factor(df$household_toilet)
describe(df$household_toilet)
tabpct(df$facility_name,df$household_toilet)

## Household fuel

df$household_fuel=as.factor(df$household_fuel)
describe(df$household_fuel)
tabpct(df$facility_name,df$household_fuel)

## Household water located in house

df$household_water_loc=as.factor(df$household_water_loc)
describe(df$household_water_loc)
tabpct(df$facility_name,df$household_water_loc)

## Household floor

df$household_floor=as.factor(df$household_floor)
describe(df$household_floor)
tabpct(df$facility_name,df$household_floor)
```


# Table 2: Patient clinical and care seeking characteristics.


```{r,echo=FALSE,fig.show='hide'}

## Reason for visit to clinic
df$facility_choice_reason___2 = as.factor(df$facility_choice_reason___2)
describe(df$facility_choice_reason___2)
tabpct(df$facility_name,df$facility_choice_reason___2)

df$facility_choice_reason___3 = as.factor(df$facility_choice_reason___3)
describe(df$facility_choice_reason___3)
tabpct(df$facility_name,df$facility_choice_reason___3)

df$facility_choice_reason___4 = as.factor(df$facility_choice_reason___4)
describe(df$facility_choice_reason___4)
tabpct(df$facility_name,df$facility_choice_reason___4)

df$facility_choice_reason___5 = as.factor(df$facility_choice_reason___5)
describe(df$facility_choice_reason___5)
tabpct(df$facility_name,df$facility_choice_reason___5)

df$facility_choice_reason___8 = as.factor(df$facility_choice_reason___8)
describe(df$facility_choice_reason___8)
tabpct(df$facility_name,df$facility_choice_reason___8)

## ## Mode of travel to clinic

df$travel_mode___1=as.factor(df$travel_mode___1) 
describe(df$travel_mode___1)
tabpct(df$facility_name,df$travel_mode___1)

df$travel_mode___2=as.factor(df$travel_mode___2)
describe(df$travel_mode___2)

df$travel_mode___3=as.factor(df$travel_mode___3)
describe(df$travel_mode___3)
tabpct(df$facility_name,df$travel_mode___3)

df$travel_mode___4=as.factor(df$travel_mode___4)
describe(df$travel_mode___4)

df$travel_mode___5=as.factor(df$travel_mode___5) 
describe(df$travel_mode___5)

df$travel_mode___6=as.factor(df$travel_mode___6)
describe(df$travel_mode___6)
tabpct(df$facility_name,df$travel_mode___6)

df$travel_mode___7=as.factor(df$travel_mode___7)
describe(df$travel_mode___7)
tabpct(df$facility_name,df$travel_mode___7)

df$travel_mode___8=as.factor(df$travel_mode___8)
describe(df$travel_mode___8)
tabpct(df$facility_name,df$travel_mode___8)

df$travel_mode___11=as.factor(df$travel_mode___11)
describe(df$travel_mode___11)
tabpct(df$facility_name,df$travel_mode___11)


## Travel time to arrive at clinic
df$travel_time[df$travel_time==999] = NA
df$travel_time[df$travel_time==99] = NA
df$travel_time=as.factor(df$travel_time)
describe(df$travel_time)
tabpct(df$facility_name,df$travel_time)

## Estimated amount of money spent for transport to arrive at clinic (USD)
df$travel_cost[df$travel_cost==999] = NA
df$travel_cost[df$travel_cost==99] = NA
df$travel_cost=as.factor(df$travel_cost)
describe(df$travel_cost)
tabpct(df$facility_name,df$travel_cost)

```


# Table 3: Use of PO device across facilities.

```{r,echo=FALSE,fig.show='hide'}

## PO device used during encounter
df$used_po_yn=as.factor(df$used_po_yn)
describe(df$used_po_yn)

## PO device used correctly
df$correct_use_yn=as.factor(df$correct_use_yn)
describe(df$correct_use_yn)
tabpct(df$facility_name,df$correct_use_yn)

## Duration of PO device use
df$po_stop1 <- as.POSIXct(df$po_stop, format="%d/%m/%Y %H:%M")
df$po_start1 <- as.POSIXct(df$po_start, format="%d/%m/%Y %H:%M")
df$duration_po =difftime(df$po_stop1,df$po_start1, units = "mins")
df$duration_po=as.numeric(df$duration_po)
summ(df$duration_po)
df$duration_po_1 = cut(df$duration_po,
                       breaks = c(0,1,3.1,5.1,10.1,30.1,60),
                       right = F,
                       labels = c("Moins une min","1 à 3 m","4-5m","6-10m","11-30","31-60"))
describe(df$duration_po_1)
tabpct(df$facility_name,df$duration_po_1)

## Consultation duration
df$consult_start=as.POSIXlt(df$consult_start, format = "%H:%M")
df$consult_stop=as.POSIXct(df$consult_stop, format = "%H:%M")
df$consultation_duration = difftime(df$consult_stop,df$consult_start,units = "mins")
df$consultation_duration=as.numeric(df$consultation_duration)
summ(df$consultation_duration)
df$consultation_duration_1 = cut(df$consultation_duration,
                       breaks = c(0,2.1,5.1,10.1,30.1,60.1,100),
                       right = F,
                       labels = c("2 min","3-5m","6-10m","11-30","31-60","Plus 60"))
describe(df$consultation_duration_1)
tabpct(df$facility_name,df$consultation_duration_1)

## Encounters where all clinical measurements were assessed

df$correct_use_measurements = df$correct_use_measurements___1 + df$correct_use_measurements___2 +
  df$correct_use_measurements___3 + df$correct_use_measurements___4
df$correct_use_measurements=as.factor(df$correct_use_measurements)
describe(df$correct_use_measurements)
tabpct(df$facility_name,df$correct_use_measurements)
```


# Table 4: Clinical outcomes following implementation of PO device.
