---
title: "Rapport Etude implementation"
author: "Senegal data manager"
date: "2024-02-28"
output: word_document
---

Resultats 

```{r,echo=FALSE,results='hide'}

df_og <- read.csv2("C:/Users/user/Dropbox/Mon PC (DESKTOP-OMJATUN)/Desktop/TIMCI/Implamentation study training/implementation-data_clean_2024-02-15.csv")
# Define country and subset

df1 <- subset(df_og, df_og$country=="Senegal")
library(plyr)
library(dplyr)
library(tableone)
library(knitr)
library(kableExtra)
library(epiDisplay)
library(Hmisc)

```

# Table 1: Patient demographic and household characteristics.

```{r,echo=FALSE,fig.show='hide'}
 
## Age
df1$birthday<-as.Date(paste(df1$birth_year,df1$birth_month,"15",sep = "-"),format = "%Y-%m-%d")
df1$visit_date_1=as.Date(df1$visit_date,format = "%d/%m/%Y")
df1$visit_date_2=format(df1$visit_date_1,"%Y-%m-%d")
df1$Age_categ = difftime(df1$visit_date_2,df1$birthday,units = "days")
df1$age_m = df1$Age_categ/30
df1$age_m=as.numeric(df1$age_m)
df1$age_m_1 = cut(df1$age_m,
             breaks = c(0,2,12,60),
             right = F,
             labels = c("0-1","2-11","12-59"))
describe(df1$age_m_1)
tabpct(df1$facility_name,df1$age_m_1)

## Sex

df1$sex=as.factor(df1$sex)
describe(df1$sex)
tabpct(df1$facility_name,df1$sex)

## Relationship of caregiver to child

describe(df1$cg_relationship)
tabpct(df1$facility_name,df1$cg_relationship)

## Caregiver age
summ(df1$cg_age)
 tapply(df1$cg_age, df1$facility_name, mean,na.rm=T)

## Maternal education
df1$cg_edu_mother[df1$cg_edu_mother==999] = NA
df1$cg_edu_mother=as.factor(df1$cg_edu_mother)
describe(df1$cg_edu_mother)
tabpct(df1$facility_name,df1$cg_edu_mother)

## Household head
df1$household_head[df1$household_head==99] = NA
df1$household_head=as.factor(df1$household_head)
describe(df1$household_head)
tabpct(df1$facility_name,df1$household_head)

## Household toilet
df1$household_toilet[df1$household_toilet==999] = NA
df1$household_toilet=as.factor(df1$household_toilet)
describe(df1$household_toilet)
tabpct(df1$facility_name,df1$household_toilet)

## Household fuel

df1$household_fuel=as.factor(df1$household_fuel)
describe(df1$household_fuel)
tabpct(df1$facility_name,df1$household_fuel)

## Household water located in house

df1$household_water_loc=as.factor(df1$household_water_loc)
describe(df1$household_water_loc)
tabpct(df1$facility_name,df1$household_water_loc)

## Household floor

df1$household_floor=as.factor(df1$household_floor)
describe(df1$household_floor)
tabpct(df1$facility_name,df1$household_floor)

```

# Table 2: Patient clinical and care seeking characteristics

```{r,echo=FALSE,fig.show='hide'}
## Reason for visit to clinic
df1$facility_choice_reason___2 = as.factor(df1$facility_choice_reason___2)
describe(df1$facility_choice_reason___2)
tabpct(df1$facility_name,df1$facility_choice_reason___2)

df1$facility_choice_reason___3 = as.factor(df1$facility_choice_reason___3)
describe(df1$facility_choice_reason___3)
tabpct(df1$facility_name,df1$facility_choice_reason___3)

df1$facility_choice_reason___4 = as.factor(df1$facility_choice_reason___4)
describe(df1$facility_choice_reason___4)
tabpct(df1$facility_name,df1$facility_choice_reason___4)

df1$facility_choice_reason___5 = as.factor(df1$facility_choice_reason___5)
describe(df1$facility_choice_reason___5)
tabpct(df1$facility_name,df1$facility_choice_reason___5)

df1$facility_choice_reason___8 = as.factor(df1$facility_choice_reason___8)
describe(df1$facility_choice_reason___8)
tabpct(df1$facility_name,df1$facility_choice_reason___8)

## ## Mode of travel to clinic

df1$travel_mode___1=as.factor(df1$travel_mode___1) 
describe(df1$travel_mode___1)
tabpct(df1$facility_name,df1$travel_mode___1)

df1$travel_mode___2=as.factor(df1$travel_mode___2)
describe(df1$travel_mode___2)

df1$travel_mode___3=as.factor(df1$travel_mode___3)
describe(df1$travel_mode___3)
tabpct(df1$facility_name,df1$travel_mode___3)

df1$travel_mode___4=as.factor(df1$travel_mode___4)
describe(df1$travel_mode___4)

df1$travel_mode___5=as.factor(df1$travel_mode___5) 
describe(df1$travel_mode___5)

df1$travel_mode___6=as.factor(df1$travel_mode___6)
describe(df1$travel_mode___6)
tabpct(df1$facility_name,df1$travel_mode___6)

df1$travel_mode___7=as.factor(df1$travel_mode___7)
describe(df1$travel_mode___7)
tabpct(df1$facility_name,df1$travel_mode___7)

df1$travel_mode___8=as.factor(df1$travel_mode___8)
describe(df1$travel_mode___8)
tabpct(df1$facility_name,df1$travel_mode___8)

df1$travel_mode___11=as.factor(df1$travel_mode___11)
describe(df1$travel_mode___11)
tabpct(df1$facility_name,df1$travel_mode___11)



## Travel time to arrive at clinic

df1$travel_time[df1$travel_time==999] = NA
df1$travel_time[df1$travel_time==99] = NA
df1$travel_time=as.factor(df1$travel_time)
describe(df1$travel_time)
tabpct(df1$facility_name,df1$travel_time)

## Estimated amount of money spent for transport to arrive at clinic (USD)
df1$travel_cost[df1$travel_cost==999] = NA
df1$travel_cost[df1$travel_cost==99] = NA
df1$travel_cost=as.factor(df1$travel_cost)
describe(df1$travel_cost)
tabpct(df1$facility_name,df1$travel_cost)
```

# Table 3: Use of PO device across facilities.

```{r,echo=FALSE,fig.show='hide'}
## PO device used during encounter

df1$used_po_yn=as.factor(df1$used_po_yn)
describe(df1$used_po_yn)

## PO device used correctly

df1$correct_use_yn=as.factor(df1$correct_use_yn)
describe(df1$correct_use_yn)
tabpct(df1$facility_name,df1$correct_use_yn)

## Duration of PO device use
df1$po_stop1 <- as.POSIXct(df1$po_stop, format="%d/%m/%Y %H:%M")
df1$po_start1 <- as.POSIXct(df1$po_start, format="%d/%m/%Y %H:%M")
df1$duration_po =difftime(df1$po_stop1,df1$po_start1, units = "mins")
df1$duration_po=as.numeric(df1$duration_po)
summ(df1$duration_po)
df1$duration_po_1 = cut(df1$duration_po,
                       breaks = c(0,1,3.1,5.1,10.1,30.1,60),
                       right = F,
                       labels = c("Moins une min","1 à 3 m","4-5m","6-10m","11-30","31-60"))
describe(df1$duration_po_1)
tabpct(df1$facility_name,df1$duration_po_1)

## Consultation duration
df1$consult_start=as.POSIXlt(df1$consult_start, format = "%H:%M")
df1$consult_stop=as.POSIXct(df1$consult_stop, format = "%H:%M")
df1$consultation_duration = difftime(df1$consult_stop,df1$consult_start,units = "mins")
df1$consultation_duration=as.numeric(df1$consultation_duration)
summ(df1$consultation_duration)
df1$consultation_duration_1 = cut(df1$consultation_duration,
                       breaks = c(0,2.1,5.1,10.1,30.1,60.1,100),
                       right = F,
                       labels = c("2 min","3-5m","6-10m","11-30","31-60","Plus 60"))
describe(df1$consultation_duration_1)
tabpct(df1$facility_name,df1$consultation_duration_1)

## Encounters where all clinical measurements were assessed

df1$correct_use_measurements = df1$correct_use_measurements___1 + df1$correct_use_measurements___2 +
  df1$correct_use_measurements___3 + df1$correct_use_measurements___4
df1$correct_use_measurements=as.factor(df1$correct_use_measurements)
describe(df1$correct_use_measurements)
tabpct(df1$facility_name,df1$correct_use_measurements)

```

# Table 4: Clinical outcomes following implementation of PO device

